CREATE DATABASE IF NOT EXISTS fivejars;
USE fivejars;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    nickname VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    balance DECIMAL(14,2) DEFAULT 0.00,
    coefficient DECIMAL(4,3) DEFAULT 0.000,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);